controllers:
    resource:
        prefix: /api/
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

pizzas:
    path: /api/pizzas
    controller: App\Controller\PizzasController::pizzas
    methods: GET
